### PR TITLE
Mobile menu feature

### PR DESCRIPTION
**Pull request by JbirdL86**
In this branch we've implemented an interactive menu that hides and shows according to its current status. The main files modified during the creation of this feature were:

- index.html
- style.css
- nav.js

I hope you like my project so far! Thanks for your feedback! :+1:

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
Hi @JbirdL86, 

Good job so far! 🔥🔥 You are already there, just remember the linters config!

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] **Right now you only have two linters, Eslint and Stylelint, you need to add the Webhint linter on your linters.yml file, [check this link](https://github.com/microverseinc/linters-config/tree/master/html-css-js) for instructions.**

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

almost there

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by JbirdL86** [comment]
I'm not sure what to do here..... I followed the instructions on this link https://github.com/microverseinc/linters-config/tree/master/javascript as part of the exercise. Please advise @mricanho.

**Comment by mricanho** [comment]
> I'm not sure what to do here..... I followed the instructions on this link https://github.com/microverseinc/linters-config/tree/master/javascript as part of the exercise. Please advise @mricanho.

You only need to add the hint linter, because you are using HTML, CSS and JS, so, follow this instructions: https://github.com/microverseinc/linters-config/tree/master/html-css-js

**Review by vichuge — APPROVED** [review]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

InbornCandidHornet-size_restricted

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
